// Generated by https://quicktype.io

export interface QuizResponse {
  response_code: number
  results: QuizQuestion[]
}

export interface QuizQuestion {
  category: string
  type: Type
  difficulty: Difficulty
  question: string
  correct_answer: string
  incorrect_answers: string[]
}

export enum Difficulty {
  EASY = 'easy',
  MEDIUM = 'medium',
  HARD = 'hard',
}

export enum Type {
  BOOLEAN = 'boolean',
  MULTIPLE = 'multiple',
}
